### ISSUE TITLE
undefined method `feature_flag' for Bundler:Module

### ISSUE THREAD

**Issue by steakknife** [bkuhlmann/gemsmith#7]
## Overview

`Rakefile` header is missing the standard `bundle exec ` cli prefix obsoleting code:

```ruby
require "bundler/setup" if File.exist?(File.expand_path("Gemfile", __dir__))
```

## With the above code

```
$ rake build
Cleaned gem artifacts.
Updated gem table of contents.
Build failed: Gem has uncommitted changes
$
```

## Stacktrace WITHOUT

```
$ rake build
rake aborted!
NoMethodError: undefined method `feature_flag' for Bundler:Module
~/.gem/ruby/2.5.1/gems/bundler-1.16.4/lib/bundler/ui/shell.rb:44:in `error'
~/.gem/ruby/2.5.1/gems/gemsmith-12.3.0/lib/gemsmith/rake/builder.rb:30:in `validate'
~/.gem/ruby/2.5.1/gems/gemsmith-12.3.0/lib/gemsmith/rake/tasks.rb:47:in `block in install'
~/.gem/ruby/2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => build => validate
(See full trace by running task with --trace)
$
```

## Steps to Recreate

1. Create a new gem
2. Run `rake build`

## the-gem.gemspec

```ruby
spec.add_dependency "thor", "~> 0.20"
spec.add_development_dependency "gemsmith", "~> 12.3"
```

## 

## Environment
- macOS 10.13.6
- Ruby 2.5.1
- Gemsmith 12.3.0
- Bundler 1.16.4

**Comment by bkuhlmann** [comment]
Thanks for reporting this. Can you run `bundle exec rake build` instead and let me know if the error persists? By running `rake build` only, you are most likely picking up an older version of Bundler. The common practice is to precede execution with `bundle exec` before running your commands so the version of Bundler (as defined in the Gemfile) is honored.

**Comment by bkuhlmann** [comment]
Can you also confirm that your generated `Rakefile` looks, roughly, like this (depending on which options you gave Gemsmith when building the gem):

```
   1   │ # frozen_string_literal: true
   2   │
   3   │ begin
   4   │   require "gemsmith/rake/setup"
   5   │   require "bundler/audit/task"
   6   │   require "git/cop/rake/setup"
   7   │   require "rspec/core/rake_task"
   8   │   require "reek/rake/task"
   9   │   require "rubocop/rake_task"
  10   │
  11   │   Bundler::Audit::Task.new
  12   │   RSpec::Core::RakeTask.new(:spec)
  13   │   Reek::Rake::Task.new
  14   │   RuboCop::RakeTask.new
  15   │ rescue LoadError => error
  16   │   puts error.message
  17   │ end
  18   │
  19   │ desc "Run code quality checks"
  20   │ task code_quality: %i[bundle:audit git_cop reek rubocop]
  21   │
  22   │ task default: %i[code_quality spec]
```

The critical line you are looking for is, Line 4.

**Comment by steakknife** [comment]
Can't repro, must be refactoring PEBKAC. 🤣 False alarm ⏰ 

✌️ 

`gemsmith -g deleteme --no-guard --pry --rspec --git-hub --git-cop --cli --bundler-audit --circle-ci --rubocop --security && cd deleteme && bundle && rake`

```ruby
# frozen_string_literal: true

begin
  require "gemsmith/rake/setup"
  require "bundler/audit/task"
  require "git/cop/rake/setup"
  require "rspec/core/rake_task"
  require "reek/rake/task"
  require "rubocop/rake_task"

  Bundler::Audit::Task.new
  RSpec::Core::RakeTask.new(:spec)
  Reek::Rake::Task.new
  RuboCop::RakeTask.new
rescue LoadError => error
  puts error.message
end

desc "Run code quality checks"
task code_quality: %i[bundle:audit git_cop reek rubocop]

task default: %i[code_quality spec]
```

**Comment by bkuhlmann** [comment]
Awesome, good to hear you are back to smithing new gems. :)
